// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StorhaugenEats.API.Data;

#nullable disable

namespace StorhaugenEats.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251218115333_AddCollectionVisibility")]
    partial class AddCollectionVisibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StorhaugenEats.API.Models.ActivityFeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("activity_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("metadata");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("activity_feed", (string)null);
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<bool>("IsShared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_shared");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("UniqueShareId")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("unique_share_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("UniqueShareId")
                        .IsUnique();

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.CollectionMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("member")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("CollectionId", "UserId")
                        .IsUnique();

                    b.ToTable("collection_members", (string)null);
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.EtlSyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuildId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("build_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("RecipesAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("recipes_added");

                    b.Property<int>("RecipesUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("recipes_updated");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("hellofresh")
                        .HasColumnName("sync_type");

                    b.Property<string>("WeeksSynced")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("weeks_synced");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("etl_sync_log", (string)null);
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.GlobalRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("average_rating");

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cook_time_minutes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Cuisine")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cuisine");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("difficulty");

                    b.Property<string>("HellofreshSlug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hellofresh_slug");

                    b.Property<string>("HellofreshUuid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hellofresh_uuid");

                    b.Property<string>("HellofreshWeek")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hellofresh_week");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("image_urls");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("ingredients");

                    b.Property<bool>("IsEditable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_editable");

                    b.Property<bool>("IsHellofresh")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hellofresh");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("NutritionData")
                        .HasColumnType("jsonb")
                        .HasColumnName("nutrition_data");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_time_minutes");

                    b.Property<Guid?>("PublishedFromUserRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_from_user_recipe_id");

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_count");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("integer")
                        .HasColumnName("total_ratings");

                    b.Property<int?>("TotalTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("total_time_minutes");

                    b.Property<int>("TotalTimesAdded")
                        .HasColumnType("integer")
                        .HasColumnName("total_times_added");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AverageRating");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HellofreshUuid")
                        .IsUnique();

                    b.HasIndex("IsHellofresh")
                        .HasFilter("is_hellofresh = true");

                    b.HasIndex("IsPublic")
                        .HasFilter("is_public = true");

                    b.HasIndex("PublishedFromUserRecipeId");

                    b.ToTable("global_recipes", (string)null);
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GlobalRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_recipe_id");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric")
                        .HasColumnName("score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("UserRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_recipe_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserRecipeId");

                    b.HasIndex("GlobalRecipeId", "UserId")
                        .IsUnique();

                    b.ToTable("ratings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rating_Score", "score >= 0 AND score <= 10");
                        });
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.RecipeTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("recipe_tags", (string)null);
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FavoriteCuisines")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("favorite_cuisines");

                    b.Property<bool>("IsProfilePublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_profile_public");

                    b.Property<string>("SupabaseUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("supabase_user_id");

                    b.Property<string>("UniqueShareId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("unique_share_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UniqueShareId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.UserFriendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("message");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_user_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id");

                    b.HasIndex("RequesterUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("RequesterUserId", "TargetUserId")
                        .IsUnique();

                    b.ToTable("user_friendships", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserFriendship_NoSelf", "requester_user_id != target_user_id");
                        });
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.UserRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GlobalRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_recipe_id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<int?>("LocalCookTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("local_cook_time_minutes");

                    b.Property<string>("LocalCuisine")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("local_cuisine");

                    b.Property<string>("LocalDescription")
                        .HasColumnType("text")
                        .HasColumnName("local_description");

                    b.Property<string>("LocalDifficulty")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("local_difficulty");

                    b.Property<string>("LocalImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("local_image_url");

                    b.Property<string>("LocalImageUrls")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("local_image_urls");

                    b.Property<string>("LocalIngredients")
                        .HasColumnType("jsonb")
                        .HasColumnName("local_ingredients");

                    b.Property<int?>("LocalPrepTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("local_prep_time_minutes");

                    b.Property<int?>("LocalServings")
                        .HasColumnType("integer")
                        .HasColumnName("local_servings");

                    b.Property<string>("LocalTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("local_title");

                    b.Property<string>("PersonalNotes")
                        .HasColumnType("text")
                        .HasColumnName("personal_notes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("private")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GlobalRecipeId");

                    b.HasIndex("UserId");

                    b.HasIndex("Visibility");

                    b.ToTable("user_recipes", (string)null);
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.UserRecipeCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by_user_id");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<Guid>("UserRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_recipe_id");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("UserRecipeId");

                    b.HasIndex("CollectionId", "SortOrder");

                    b.HasIndex("UserRecipeId", "CollectionId")
                        .IsUnique();

                    b.ToTable("user_recipe_collections", (string)null);
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.UserRecipeTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("UserRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_recipe_id");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("UserRecipeId", "TagId")
                        .IsUnique();

                    b.ToTable("user_recipe_tags", (string)null);
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.ActivityFeedItem", b =>
                {
                    b.HasOne("StorhaugenEats.API.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.Collection", b =>
                {
                    b.HasOne("StorhaugenEats.API.Models.User", "Owner")
                        .WithMany("OwnedCollections")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.CollectionMember", b =>
                {
                    b.HasOne("StorhaugenEats.API.Models.Collection", "Collection")
                        .WithMany("Members")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StorhaugenEats.API.Models.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StorhaugenEats.API.Models.User", "User")
                        .WithMany("CollectionMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("InvitedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.GlobalRecipe", b =>
                {
                    b.HasOne("StorhaugenEats.API.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StorhaugenEats.API.Models.UserRecipe", "PublishedFromUserRecipe")
                        .WithMany()
                        .HasForeignKey("PublishedFromUserRecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("PublishedFromUserRecipe");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.Rating", b =>
                {
                    b.HasOne("StorhaugenEats.API.Models.GlobalRecipe", "GlobalRecipe")
                        .WithMany("Ratings")
                        .HasForeignKey("GlobalRecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StorhaugenEats.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StorhaugenEats.API.Models.UserRecipe", "UserRecipe")
                        .WithMany("Ratings")
                        .HasForeignKey("UserRecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GlobalRecipe");

                    b.Navigation("User");

                    b.Navigation("UserRecipe");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.RecipeTag", b =>
                {
                    b.HasOne("StorhaugenEats.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.UserFriendship", b =>
                {
                    b.HasOne("StorhaugenEats.API.Models.User", "RequesterUser")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StorhaugenEats.API.Models.User", "TargetUser")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequesterUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.UserRecipe", b =>
                {
                    b.HasOne("StorhaugenEats.API.Models.GlobalRecipe", "GlobalRecipe")
                        .WithMany()
                        .HasForeignKey("GlobalRecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StorhaugenEats.API.Models.User", "User")
                        .WithMany("UserRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalRecipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.UserRecipeCollection", b =>
                {
                    b.HasOne("StorhaugenEats.API.Models.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StorhaugenEats.API.Models.Collection", "Collection")
                        .WithMany("UserRecipeCollections")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StorhaugenEats.API.Models.UserRecipe", "UserRecipe")
                        .WithMany("UserRecipeCollections")
                        .HasForeignKey("UserRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Collection");

                    b.Navigation("UserRecipe");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.UserRecipeTag", b =>
                {
                    b.HasOne("StorhaugenEats.API.Models.RecipeTag", "Tag")
                        .WithMany("UserRecipeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StorhaugenEats.API.Models.UserRecipe", "UserRecipe")
                        .WithMany("UserRecipeTags")
                        .HasForeignKey("UserRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("UserRecipe");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.Collection", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("UserRecipeCollections");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.GlobalRecipe", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.RecipeTag", b =>
                {
                    b.Navigation("UserRecipeTags");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("CollectionMemberships");

                    b.Navigation("OwnedCollections");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("UserRecipes");
                });

            modelBuilder.Entity("StorhaugenEats.API.Models.UserRecipe", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("UserRecipeCollections");

                    b.Navigation("UserRecipeTags");
                });
#pragma warning restore 612, 618
        }
    }
}
