// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StorhaugenEats.API.Data;

#nullable disable

namespace StorhaugenEats.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214100000_AddCollections")]
    partial class AddCollections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: This is a partial migration designer. The full model snapshot
            // is maintained in AppDbContextModelSnapshot.cs
            // This migration adds: collections, collection_members, user_recipe_collections tables
#pragma warning restore 612, 618
        }
    }
}
